<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '3874be18f5e36fbf96e9b3727e7f4161',
  'DATABASE_URL' => 'mysql://lerameauzjtest:Spokefclm09@lerameauzjtest.mysql.db/lerameauzjtest?serverVersion=5.6',
  'MAILER_URL' => 'gmail://egliselerameau@gmail.com:OvZ.81SayE@localhost',
);
