<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMoaZ9AV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMoaZ9AV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMoaZ9AV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMoaZ9AV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMoaZ9AV\App_KernelDevDebugContainer([
    'container.build_hash' => 'MoaZ9AV',
    'container.build_id' => '4b69fdf0',
    'container.build_time' => 1588254888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMoaZ9AV');
